### ISSUE TITLE
Isn't work in android 11

### ISSUE THREAD

**Issue by Stu75e** [CodeDead/DeadHash-android#39] opened 2023-12-13 04:25 UTC
Can't add files to the app
Version 1.8.1 f-droid

**Comment by CodeDead** [comment] 2023-12-13 08:18
Duplicate of https://github.com/CodeDead/DeadHash-android/issues/37

This has been fixed in the latest version 1.8.2 (which will probably be available on FDroid soon, but you can already download a signed apk from Github)

**Closed** 2023-12-13 08:19 UTC
